### ISSUE TITLE
submenu() doesn't hide hidden pages

### ISSUE THREAD

**Issue by manu37** [cmb69/register_xh#47] opened 2017-07-11 16:06 UTC
toc() respects hidden pages according to config, submenu() (inside page) doesn't.

**Comment by cmb69** [comment] 2017-07-11 16:14
Hmm, isn't that a CMSimple_XH issue?

**Comment by manu37** [comment] 2017-07-11 16:16
CMSimple 1.6.9
just rechecked. toc() also reveales hidden pages.

**Comment by cmb69** [comment] 2017-07-11 16:21
> just rechecked. toc() also reveales hidden pages.

If that is about Register_XH it's a duplicate of #45. See https://cmsimpleforum.com/viewtopic.php?f=12&t=12862#p61190 ff for a quick fix.

**Closed as completed by cmb69** 2017-07-11 16:21 UTC
Labels: duplicate
